config/routes.rb
Rails.application.routes.draw do
  resources :flats
  root to: "flats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def show
  end

  def edit
  end

  def update
    @flat.update(flat_params)
  end

  def destroy
    @flat.destroy
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h2>All our Flats (<%= @flats.count %>)</h2>
<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-xs-12 col-md-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
        <div class="card-category"><%= flat.address %></div>
        <div class="card-description">
          <h2><%= flat.name %></h2>
          <p><%= flat.description %></p>
        </div>
        <div class="card-stats">
          <i class="material-icons" style="margin-right: 5px">group</i><p><%= flat.number_of_guests %></p>
          <i class="material-icons">attach_money</i><p><%= flat.price_per_night %></p>
        </div>
        <%= link_to '', flat_path(flat), class: 'card-link' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
  <% if @flat.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @flat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name, wrapper_html: { class: 'form-group' } %>
  <%= f.input :description, wrapper_html: { class: 'form-group' } %>
  <%= f.input :address, wrapper_html: { class: 'form-group' } %>
  <%= f.input :number_of_guests, collection: (1..12), wrapper_html: { class: 'form-group' } %>
  <%= f.input :price_per_night, wrapper_html: { class: 'form-group' } %>
  <%= f.submit "Add Flat", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h3>Simple Airbnb</h3>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Links -->
    <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary" %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="material-icons" data-toggle="dropdown">menu</i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Add Flat</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>